# jdk8 for ubuntu-zh_CN 16.04
# Version: u102
FROM registry.nanoframework.org:5000/ubuntu-zh_cn:16.04
MAINTAINER River Yang "comicme_yanghe@icloud.com"

ADD jdk-8u102-linux-x64.tar.gz /usr/local/
ENV JAVA_HOME /usr/local/jdk1.8.0_102
ENV PATH $JAVA_HOME/bin:$PATH
ENV CLASSPATH .:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

