# Redis for ubuntu 14.04
# Version: 1.0.0

FROM ubuntu:14.04
MAINTAINER River Yang "comicme_yanghe@icloud.com"

ADD sources.list /etc/apt/
RUN apt-get update
RUN apt-get install -y redis-tools

CMD [ "/bin/bash" ]
