# Java8u45 base mirror on CentOS 6.6
# Version: 1.0.0
FROM centos:6.6
MAINTAINER River Yang "comicme_yanghe@icloud.com"

ADD jdk-8u45-linux-x64.tar.gz /usr/local/
ENV JAVA_HOME /usr/local/jdk1.8.0_45
ENV PATH $JAVA_HOME/bin:$PATH
ENV CLASSPATH .:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar


