# Nano App for Nginx base
# Version 0.0.1

FROM registry.nanoframework.org:5000/nginx-base:1.0
MAINTAINER River Yang "comicme_yanghe@icloud.com"

ADD webapp.conf /etc/nginx/conf.d/

EXPOSE 7000

CMD [ "nginx" ]
