# CentOS 6.6 Nginx Container
# Version: 1.0.0

FROM centos:6.6
MAINTAINER River Yang "comicme_yanghe@icloud.com"
RUN apt-get update
RUN apt-get install -y nginx
RUN echo 'Hello, Docker Nginx Container Mirror' > /usr/share/nginx/html/index.html
EXPOSE 80
